version: "3"
services:
  app:
    build: .
    volumes:
      - .:/my_app
    environment:
      - LANG=ja_JP.UTF-8
      - LC_CTYPE=ja_JP.UTF-8
    command: bash -c "rm -f spec/dummy/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"